### ISSUE TITLE
CSS does not include styles for JQuery UI 1.9 Tooltip

### ISSUE THREAD

**Issue by sanelson2000** [taitems/Aristo-jQuery-UI-Theme#56]
Tooltip was added in JQuery UI 1.9, but the styles needed to display it are missing in Aristo.  The CSS should at least include the following code, if not custom styled for Aristo.

``` css
.ui-tooltip {
    padding: 8px;
    position: absolute;
    z-index: 9999;
    max-width: 300px;
    -webkit-box-shadow: 0 0 5px #aaa;
    box-shadow: 0 0 5px #aaa;
}
body .ui-tooltip {
    border-width: 2px;
}
```
